name = "wordle-multiplayer"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[d1_databases]]
binding = "WORDLE_DB"
database_name = "wordle_d1"
database_id = "602f0f7e-4e01-4291-b888-12d8b3187794"
migrations_dir = "./migrations"

